### ISSUE TITLE
tagline 

### ISSUE THREAD

**Issue by AlonBru** [trodelgal/My-ticket-manager#3]
your tagline "WE HERE TO HELP OUR CLIENTS" is cut short ( at least on my screen)

![image](https://user-images.githubusercontent.com/66993391/91660556-58ffff00-eadf-11ea-8fa6-e0ab33a45f42.png)

it is hidden behind the blue part. also is in a similar colour so would no show if it was above the blue.
the problem intensifies when the screen narrows further

![image](https://user-images.githubusercontent.com/66993391/91660601-a9775c80-eadf-11ea-85ae-b83e272f6128.png)
![image](https://user-images.githubusercontent.com/66993391/91660612-b2682e00-eadf-11ea-9454-cc424bd54bf8.png)

**Comment by trodelgal** [comment]
fixed
